// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WLVSTools.Web.Infrastructure.ExceptionsLogging;

#nullable disable

namespace WLVSTools.Web.Migrations.ExceptionLoggingDb
{
    [DbContext(typeof(ExceptionLoggingDbContext))]
    partial class ExceptionLoggingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WLVSTools.Web.Infrastructure.ExceptionsLogging.ExceptionLogging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifyDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExceptionLoggings");
                });
#pragma warning restore 612, 618
        }
    }
}
