// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WLVSTools.Web.Infrastructure.Lotto;

#nullable disable

namespace WLVSTools.Web.Migrations.LottoDb
{
    [DbContext(typeof(LottoDbContext))]
    partial class LottoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WLVSTools.Web.Infrastructure.Lotto.LottoResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Combinations")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DrawDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("JackpotPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("LottoGame")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifyDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Winners")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LottoResults");
                });
#pragma warning restore 612, 618
        }
    }
}
